### PR TITLE
Add TypeScript types

### PR DESCRIPTION
**Pull request by SConaway**
This PR adds types to the package. The TypeScript declaration file will allow editors (such as VSCode) to provide code completion when using this package. 

Tested this using my app and manually making the changes contained in this PR. 

Since the example app is built with such an old version of react-native, would a PR upgrading it to the latest version be accepted?

### CODE REVIEW

**Comment by yairba** [comment]
Hi @SConaway, any chance you can email us to support? I need your t-shirt size :)

**Comment by SConaway** [comment]
What email should I email?

**Comment by diegoperini** [comment]
Hi @SConaway,

Thanks for the hard work! This is a great PR and we'll merge it after playing with it in VSCode a little.

An email to support@testfairy.com with the title "My t-shirt size" will be enough. 👕

I'd love to hear your ideas about how we can improve this project further.

> Since the example app is built with such an old version of react-native, would a PR upgrading it to the latest version be accepted?

That's a very good question. 

We keep RN version in the example app old on purpose, to be able to test whether new features introduce incompatibilities. It serves the purpose of being a somewhat good representation of a real world app in the app stores.

To address the issue of having the package tested in an app with the latest RN version, we created a CI script to build an example app from scratch on `git push`. https://github.com/testfairy/react-native-testfairy/blob/master/.github/workflows/build.yml

A PR updating the version in the example app is therefore unnecessary.

**Comment by SConaway** [comment]
Done. 

That makes sense.

**Comment by SConaway** [comment]
Hey there, just seeing how things are going on this PR...any chance it could get merged soon?

**Pull request merged**
